on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: A job for hello
    steps:
      - name: Hello World action steps try
        id: hello
        uses: Roizz-soul/barsoom@0.0.2
        with:
          name: 'Barsoom'