on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: A job for hello
    steps:
      - name: Hello World action steps try
        id: hello
        uses: Roizz-soul/barsoom@0.04
        with:
          name: 'Brown'
      - name: Get the output
        run: echo "The time was ${{ steps.hello.outputs.greeting }}"